[phases.setup]
nixPkgs = ["nodejs_18", "npm-9_x", "python3", "gcc", "gnumake"]

[phases.install]
cmds = ["npm install --production=false"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm run start"